### ISSUE TITLE
Implement support for the second number

### ISSUE THREAD

**Issue by iampava** [damdiana/calculator-practice#4]
You should use the same event listeners as for the first number, but decide whether to change the second one. You can do this based on the `operation` value.

Meaning, if I click `1` and the `operation` value is set, I know that now I must set `nr2` to value `1`.

So, to recap. Once we set the `operation` variable, following digit - `0, 1, ..., 9` clicks will modify `nr2`.

**Comment by damdiana** [comment]
done
