### ISSUE TITLE
Implement support for showing the result and clearing previous variables

### ISSUE THREAD

**Issue by iampava** [damdiana/calculator-practice#5]
When clicking the `=` button, you should:

1. check what `operation` we have.
1.1 if we have `+` then write in a `div` (you can do this using `innerHTML`) the sum of `nr1` and `nr2`
1.2 if we have `-` then write in a `div` (you can do this using `innerHTML`) the difference of `nr1` and `nr2`
2. clear all variable values to reset the state. Meaning, we'll assign `0` to both `nr1` and `nr2` and also we'll assign `undefined` to `operation`.

**Comment by damdiana** [comment]
done
